site_name: Arquitetura e Desenho de Software

site_description: Site de documentação do projeto MyGov

extra_css:
  - stylesheets/extra.css

plugins: []

copyright: Copyright &copy; 2024 Grupo 03

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UnBArqDsw2024-1/2024.1_G3_My_gov
      name: Repositório do grupo
    - icon: material/school
      link: https://aprender3.unb.br/
      name: Ambiente Virtual de Aprendizagem

theme:
  name: material
  language: pt-BR
  favicon: Assets/favicon.png
  logo: Assets/logo.png
  font: 
    text: Roboto
    code: Roboto Mono
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github


  palette: 
    - scheme: default
      primary: custom
      accent: custom
  
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.indexes

nav:
  - Base:
    - Base/index.md
    - Design Sprint: Base/DesignSprint.md
    - Técnicas de Elicitação: 
      - Base/TecnicasElicitacao/index.md
      - Entrevista: Base/TecnicasElicitacao/Entrevista.md
      - Questionário: Base/TecnicasElicitacao/Questionario.md
      - Personas: Base/TecnicasElicitacao/Personas.md
    - Artefatos Independentes:
      - Base/ArtefatosIndependentes/index.md
      - Heat Map: Base/ArtefatosIndependentes/Heatmap.md
      - Cronograma: Base/ArtefatosIndependentes/Cronograma.md
      - Mapa Mental: Base/ArtefatosIndependentes/MapaMental.md
      - Storyboard: Base/ArtefatosIndependentes/Storyboards.md
    - Metodologia: Base/Metodologia.md
    - Participações - Base: Base/ParticipacoesBase.md
  - Modelagem:
    - Modelagem/index.md
  - Padrões de Projeto:
    - PadroesDeProjeto/index.md
  - Arquitetura de Software & Reutilização:
    - ArquiteturaReutilizacao/index.md
  - Reuniões: 
    - AtasReunioes/index.md
    - 1ª Sprint: AtasReunioes/Sprint-1.md
