# Generated by Django 5.1 on 2024-08-14 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_declaracaoretrovenda_endereco_information_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='declaracaoretrovenda',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.endereco'),
        ),
        migrations.AddField(
            model_name='declaracaoretrovenda',
            name='information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.information'),
        ),
    ]
